spring:
  application:
    name: LF8MTG
  servlet:
    multipart:
      max-file-size: "100MB"
      max-request-size: "100MB"
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
    open-in-view: true
    hibernate:
      ddl-auto: "update"
    database-platform: "org.hibernate.dialect.MariaDBDialect"
  datasource:
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: "lux"
    password: "mauer137"
    url: "jdbc:mariadb://127.0.0.1:3306/mtg_db"